model_config:
  vocab_size: 50257  # GPT2 vocabulary size
  d_model: 768       # GPT2 model dimension
  num_embeddings: 512  # VQ codebook size
  commitment_cost: 0.25  # VQ commitment cost
  aggregation_hidden_dim: 1024  # Aggregation MLP hidden dim
  num_thoughts: 4   # Number of parallel sequences
  n_positions: 1024   # Maximum sequence length
  use_pretrained_encoder: true  # Load pretrained weights for encoder
  use_pretrained_decoder: true  # and decoder
  pretrained_model_name: gpt2  # Use GPT2-Small (124M parameters)
  # # Encoder-specific configuration (smaller, more efficient)
  # encoder_n_layer: 4        # Smaller encoder
  # encoder_n_head: 4
  # encoder_n_inner: null     # Will be set to 4*d_model
  # encoder_dropout: 0.1
  # encoder_activation_function: "gelu"
  # # Decoder-specific configuration (larger, more powerful)
  # decoder_n_layer: 6        # Medium decoder for 2 thoughts
  # decoder_n_head: 6
  # decoder_n_inner: null     # Will be set to 4*d_model
  # decoder_dropout: 0.1
  # decoder_activation_function: "gelu"

training_config:
  learning_rate: 1e-5
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  use_lr_scheduler: true
  min_lr: 1e-6
  num_epochs: 5
  batch_size: 32
  gradient_clip: 1.0
  vq_loss_weight: 0.5
  quantize_cot_only: true
  save_every: 1
  checkpoint_dir: checkpoints/four_thoughts
  pad_token_id: 50256
  val_split: 0.1

  # Training abort settings
  num_measurements_per_epoch: 50  # Number of detailed metrics per epoch
  perplexity_threshold: 5
  minimum_batches_for_checkpoint: 200
  perplexity-window-size: 20

  # Codebook tracking settings
  codebook_sample_size: 100
  codebook_tracking_enabled: true

  # Memory optimization settings
  use_mixed_precision: true
  gradient_accumulation_steps: 1
  use_gradient_checkpointing: true
  use_dynamic_batching: false  # Enable for variable sequence lengths
  max_tokens_per_batch: 4096  # Reduced for memory efficiency
  max_samples: null  # Set to a number (e.g., 1000) for debugging
  
  # Data config
  data_dir: data/GSM8K/128_128/batch_4