model_config:
  vocab_size: 50257  # GPT2 vocabulary size
  d_model: 768       # GPT2 model dimension
  num_embeddings: 512  # VQ codebook size
  commitment_cost: 0.25  # VQ commitment cost
  aggregation_hidden_dim: 1024  # Aggregation MLP hidden dim
  num_thoughts: 2   # Number of parallel sequences
  n_positions: 1024   # Maximum sequence length
  use_pretrained_encoder: false  # Load pretrained weights for encoder
  use_pretrained_decoder: false  # and decoder
  pretrained_model_name: gpt2  # Use GPT2-Small (124M parameters)
  # Encoder-specific configuration (smaller, more efficient)
  encoder_n_layer: 4        # Smaller encoder
  encoder_n_head: 4
  encoder_n_inner: null     # Will be set to 4*d_model
  encoder_dropout: 0.1
  encoder_activation_function: "gelu"
  # Decoder-specific configuration (larger, more powerful)
  decoder_n_layer: 6        # Smaller decoder for testing
  decoder_n_head: 6
  decoder_n_inner: null     # Will be set to 4*d_model
  decoder_dropout: 0.1
  decoder_activation_function: "gelu"

training_config:
  learning_rate: 1e-4
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  use_lr_scheduler: true
  min_lr: 1e-6
  num_epochs: 1
  batch_size: 1  # Very small batch size for memory efficiency
  gradient_clip: 1.0
  vq_loss_weight: 1.0
  quantize_cot_only: true
  save_every: 1
  checkpoint_dir: checkpoints/test_config
  pad_token_id: 50256
  val_split: 0.5
  num_measurements_per_epoch: 10  # Number of detailed metrics per epoch
  
  # Memory optimization settings
  use_mixed_precision: true
  gradient_accumulation_steps: 1
  use_gradient_checkpointing: true
  use_dynamic_batching: false
  max_tokens_per_batch: 4096  # Reduced for memory efficiency
  max_samples: 100  # Set to a number (e.g., 1000) for debugging
  
  # Data config
  data_dir: data/GSM8K/128_128/batch_2